export const ROLE_PROFILES = {
  software_engineering: {
    label: 'Software Engineering',
    requiredSkills: ['javascript', 'react', 'api', 'git'],
    preferredSkills: ['node', 'sql', 'testing', 'typescript', 'python'],
    keywords: ['software', 'engineer', 'frontend', 'backend', 'full-stack', 'product'],
    degrees: ['computer science', 'information technology', 'engineering'],
  },
  data_analytics: {
    label: 'Data Analytics',
    requiredSkills: ['sql', 'excel', 'data analysis'],
    preferredSkills: ['python', 'tableau', 'power bi', 'r', 'statistics'],
    keywords: ['analytics', 'dashboard', 'insights', 'reporting', 'metrics'],
    degrees: ['data science', 'statistics', 'business analytics', 'computer science'],
  },
  product: {
    label: 'Product',
    requiredSkills: ['requirements', 'roadmap', 'stakeholder', 'communication'],
    preferredSkills: ['analytics', 'user research', 'figma', 'sql'],
    keywords: ['product', 'launch', 'customer', 'prioritization', 'strategy'],
    degrees: ['business', 'computer science', 'information systems'],
  },
  cybersecurity: {
    label: 'Cybersecurity',
    requiredSkills: ['security', 'networking', 'linux'],
    preferredSkills: ['cloud', 'python', 'incident response', 'vulnerability', 'siem'],
    keywords: ['threat', 'vulnerability', 'monitoring', 'risk', 'detection'],
    degrees: ['cybersecurity', 'computer science', 'information technology'],
  },
  business: {
    label: 'Business',
    requiredSkills: ['excel', 'communication', 'analysis'],
    preferredSkills: ['sql', 'strategy', 'finance', 'operations'],
    keywords: ['business', 'stakeholder', 'process', 'client', 'operations'],
    degrees: ['business', 'finance', 'economics', 'supply chain'],
  },
  design: {
    label: 'Design',
    requiredSkills: ['design', 'figma', 'user research'],
    preferredSkills: ['prototyping', 'accessibility', 'visual design', 'ux'],
    keywords: ['design', 'user', 'prototype', 'interface', 'research'],
    degrees: ['design', 'human computer interaction', 'digital media'],
  },
};

export const KNOWN_SKILLS = [
  'accessibility',
  'api',
  'aws',
  'azure',
  'c++',
  'cloud',
  'communication',
  'css',
  'data analysis',
  'docker',
  'excel',
  'figma',
  'firebase',
  'git',
  'html',
  'incident response',
  'java',
  'javascript',
  'linux',
  'machine learning',
  'mongodb',
  'next.js',
  'node',
  'postgres',
  'power bi',
  'python',
  'r',
  'react',
  'requirements',
  'roadmap',
  'security',
  'sql',
  'statistics',
  'supabase',
  'tableau',
  'testing',
  'typescript',
  'user research',
  'vulnerability',
];
